### ISSUE TITLE
Question about semantic segmentation

### ISSUE THREAD

**Issue by Show-han** [GitGyun/visual_token_matching#15]
Hi author, I appreciate your great work! 
I have a small question: why do you treat semantic segmentation differently compared to other dense prediction tasks in your code?
For example, in fine-tuning, you train different segmentation classes separately. But why not simply set different classes in the t_idx channel, just like other tasks? 🤔

**Comment by GitGyun** [comment]
Hi, there are several reasons to treat semantic segmentation and the other tasks differently.

1. Following binary segmentation protocol, which is common in few-shot segmentation literature, training and testing data (support and query data) for each class are different. Thus it is more convenient to separate the fine-tuning and evaluation stages for each class.

2. In the same vein, semantic segmentation performance for each channel (class) is independent of each other. Thus it is better to fine-tune them separately, while other multi-channel tasks such as surface normal are evaluated on multi-channel predictions (e.g., angle distance of Euclidean vectors).

3. Since the number of classes in semantic segmentation are much larger than other tasks, running the experiment for all channels together requires much bigger computation and memory cost.

**Comment by Show-han** [comment]
Thanks!
