### ISSUE TITLE
About non-parametric matching.

### ISSUE THREAD

**Issue by codeshop715** [GitGyun/visual_token_matching#6]
Hi KAIST team,
Your work is excellent and exciting, but I don't  understand why there is "non-parametric matching". Doesn't the Token Matching Module have parameters to learn?

**Comment by GitGyun** [comment]
Regarding your question, I understand the confusion about the term "non-parametric matching" when applied to the multi-head attention layers used in VTM. Let me clarify that the term "non-parametric matching" refers to the process by which VTM produces the label through the support labels, rather than directly mapping a query input to its corresponding label. The term "non-parametric" refers to the fact that this process does not involve directly trainable parameters.

However, you are correct that the multi-head attention layers do involve trainable parameters, which are used for encoding and decoding image and label information, as you mentioned. To be more specific, we can consider the parameters in the multi-head attention layer as parts of the encoder or decoder networks, such as the query and key projection as image encoder, value projection as label encoder, and output projection as label decoder. The remaining operations (computing similarity by dot-product followed by softmax, and linear combination of values) are non-parametric.
